<a href="https://colab.research.google.com/github/Ali-mohammadi-design/Numpy_Stack/blob/main/Dot_Product_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import math

In [41]:
a=np.array([1.0,2.0])
b=np.array([3.0,4.0])

In [4]:
a

array([1, 2, 4])

In [6]:
b

array([3, 4])

In [7]:
a*b

array([3, 8])

In [9]:
dot=0
for e,f in zip(a,b):
 dot=e*f+dot
print(dot)


11


What is zip() in Python?
The zip() function combines (zips) two or more iterables (like lists or arrays) together element by element.

Think of it as pairing socks from two drawers:

python
Copy
Edit
list1 = [1, 2]
list2 = [3, 4]
zipped = zip(list1, list2)

print(list(zipped))  # → [(1, 3), (2, 4)]
🧠 In your code:
python
Copy
Edit
a = np.array([1, 2])
b = np.array([3, 4])
dot = 0

for e, f in zip(a, b):
    dot = e * f + dot

print(dot)
Let’s break it down step by step:

zip(a, b) → pairs the first element of a with the first of b, the second with the second, etc.
→ becomes: [(1, 3), (2, 4)]

Loop runs twice:

1st loop: e = 1, f = 3 → dot = 1*3 + 0 = 3

2nd loop: e = 2, f = 4 → dot = 2*4 + 3 = 11

Final result: print(dot) → 11

In [10]:
np.sum(a*b)

np.int64(11)

In [12]:
(a*b).sum()

np.int64(11)

In [20]:
c=0
for f in a:
  c=f*f+c
d=math.sqrt(c)
d

2.23606797749979

In [49]:
def abs(r):
  c=0
  for f in r:
   c=f*f+c
  d=math.sqrt(c)
  return d

In [50]:
type(abs(a))

float

In [27]:
a

array([1, 2])

In [29]:
a.T

array([1, 2])

In [58]:
cos_ab=float((a.T*b).sum()/(abs(a)*abs(b)))

In [59]:
cos_ab

0.9838699100999074