In [1]:
import numpy as np

In [3]:
l=[1,2,3]
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
l

[1, 2, 3]

In [8]:
for e in l:
  print(e)

1
2
3


In [9]:
for e in a:
  print(e)

1
2
3


In [10]:
l.append(4)


In [11]:
l

[1, 2, 3, 4]

In [12]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

Note: array is fixed and we cannot add a new element except we would create a new array

In [15]:
l+[6]

[1, 2, 3, 4, 6]

In [16]:
a+[6]

array([7, 8, 9])

As is clear all the elements of array as summed up with the 6 (broadcasting)


But in the list the new element just added to the list (Concadination)

In [17]:
l+l

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
a+a

array([2, 4, 6])

It seems arrays more follows math!!

In [19]:
2*l

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
l+l

[1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
2*a

array([2, 4, 6])

In [22]:
a+a

array([2, 4, 6])

In [24]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [25]:
a**2

array([1, 4, 9])

Numpy in most of the situation acts as an element wise

In [26]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [27]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [28]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [29]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475])