<a href="https://colab.research.google.com/github/Ali-mohammadi-design/Numpy_Stack/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [7]:
float(a[1][0])

3.0

In [8]:
a[0,1]

np.int64(2)

In [9]:
a[:,0]

array([1, 3])

In [10]:
a[0,:]

array([1, 2])

In [11]:
a.T

array([[1, 3],
       [2, 4]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
5*np.ones([3,6])

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.random([4,5])

array([[0.97122842, 0.81650017, 0.43744884, 0.36522786, 0.25238632],
       [0.28366876, 0.90009163, 0.27642249, 0.58208345, 0.76491536],
       [0.14160736, 0.82603792, 0.49808377, 0.8252778 , 0.00209837],
       [0.25697144, 0.53346905, 0.68081682, 0.74679927, 0.54878132]])

In [21]:
a

array([[1, 2],
       [3, 4]])

In [22]:
D=np.random.randint(1,11, size=(4,4))

In [23]:
D

array([[ 7,  9,  3,  9],
       [ 1,  4, 10,  4],
       [ 2,  7, 10,  8],
       [ 7,  9,  2,  8]])

In [24]:
C=np.random.randint(1,11, size=(4,4))

In [25]:
C

array([[2, 2, 1, 7],
       [8, 1, 8, 8],
       [1, 7, 6, 7],
       [6, 9, 6, 3]])

In [26]:
L1=[[1,2,3,4],[2,3,4,5],[4,5,6,7],[6,7,8,9]]

In [27]:
L1

[[1, 2, 3, 4], [2, 3, 4, 5], [4, 5, 6, 7], [6, 7, 8, 9]]

In [28]:
L2=[[14,24,34,4],[23,3,34,5],[34,53,6,7],[62,7,82,92]]

In [29]:
L2

[[14, 24, 34, 4], [23, 3, 34, 5], [34, 53, 6, 7], [62, 7, 82, 92]]

In [30]:
import time

In [31]:
start_time=time.time()

for i in range(0,100):
  pass

end_time=time.time()

print(f"the execution time is {end_time-start_time}, and the start time is {start_time} and the end time is {end_time}")

the execution time is 0.00013136863708496094, and the start time is 1743076263.0748742 and the end time is 1743076263.0750055


In [32]:
start_time=time.time()


M=np.dot(C,D)

end_time=time.time()

print(f"the execution time is {end_time-start_time}, and the start time is {start_time} and the end time is {end_time}")

the execution time is 0.00025343894958496094, and the start time is 1743076329.551702 and the end time is 1743076329.5519555


In [33]:
start_time=time.time()


result = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

# Perform multiplication
for i in range(len(L1)):             # loop through rows of A
    for j in range(len(L1[0])):      # loop through columns of B
        for k in range(len(L2)):     # loop through rows of B
            result[i][j] += L1[i][k] * L2[k][j]

# Print result
for row in result:
    print(row)

end_time=time.time()

print(f"the execution time is {end_time-start_time}, and the start time is {start_time} and the end time is {end_time}")

[410, 217, 448, 403]
[543, 304, 604, 511]
[809, 478, 916, 727]
[1075, 652, 1228, 943]
the execution time is 0.0004589557647705078, and the start time is 1743076462.1572359 and the end time is 1743076462.1576948
