<a href="https://colab.research.google.com/github/Ali-mohammadi-design/Numpy_Stack/blob/main/Numpy_Bonus_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [32]:
a=np.array([[0.1,0.3,0.4],[0.2,0.3,0.4],[0.5,0.6,0.7]])

In [33]:
a

array([[0.1, 0.3, 0.4],
       [0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7]])

In [34]:
v=np.array([1/3,1/3,1/3])

In [36]:
v*a

array([[0.03333333, 0.1       , 0.13333333],
       [0.06666667, 0.1       , 0.13333333],
       [0.16666667, 0.2       , 0.23333333]])

In [37]:
d=[]
for i in range(25):
  v_p=v*a
  d.append(np.abs(v_p-v))
  v=v_p




In [38]:
d

[array([[0.3       , 0.23333333, 0.2       ],
        [0.26666667, 0.23333333, 0.2       ],
        [0.16666667, 0.13333333, 0.1       ]]),
 array([[0.03      , 0.07      , 0.08      ],
        [0.05333333, 0.07      , 0.08      ],
        [0.08333333, 0.08      , 0.07      ]]),
 array([[0.003     , 0.021     , 0.032     ],
        [0.01066667, 0.021     , 0.032     ],
        [0.04166667, 0.048     , 0.049     ]]),
 array([[0.0003    , 0.0063    , 0.0128    ],
        [0.00213333, 0.0063    , 0.0128    ],
        [0.02083333, 0.0288    , 0.0343    ]]),
 array([[3.00000000e-05, 1.89000000e-03, 5.12000000e-03],
        [4.26666667e-04, 1.89000000e-03, 5.12000000e-03],
        [1.04166667e-02, 1.72800000e-02, 2.40100000e-02]]),
 array([[3.00000000e-06, 5.67000000e-04, 2.04800000e-03],
        [8.53333333e-05, 5.67000000e-04, 2.04800000e-03],
        [5.20833333e-03, 1.03680000e-02, 1.68070000e-02]]),
 array([[3.00000000e-07, 1.70100000e-04, 8.19200000e-04],
        [1.70666667e-05, 1.701